data_params:
  adj_path: data/processed/co_occurrence_matrix.csv
  content_path: data/processed/order_matrix_new.csv
  dates_dict_path: data/processed/dates_dict.pkl
  dish_dict_path: data/processed/dish_dict_new.pkl
  discard_items_path: data/raw/discard_items.csv
exp_params:
  batch_size: 256
  device: cuda
  epochs: 500
  learning_rate: 0.001
  num_gnn_layers: 3
  test_model_path: /content/Restaurant-Sales-Prediction-USTGCN/work_dir/logs/run_0
logging_params:
  last_saved_model: /content/Restaurant-Sales-Prediction-USTGCN/work_dir/logs/run_0
  work_dir: /content/Restaurant-Sales-Prediction-USTGCN/work_dir
model_params:
  num_days: 30
  pred_len: 7
  test_end: 1059
  test_start: 720
  test_stride: 7
  train_end: 719
  train_start: 1
  train_stride: 1
